name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9.19
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        eval "$(conda shell.bash hook)"
        conda init bash
        source ~/.bashrc
        conda activate base
        pip install uv
        uv pip install pytest
        uv pip install -r requirements.txt
    - name: Test with pytest
      run: |
        eval "$(conda shell.bash hook)"
        conda init bash
        source ~/.bashrc
        conda activate base
        conda activate base
        wget https://zenodo.org/records/13996393/files/ligand_target_mouse.parquet -O data/ligand_target_mouse.parquet
        pytest -vv -p no:warnings
